// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7pYdGxyFPDgRQT7tJPUwb040eoWAtup0',
    appId: '1:141997769768:web:4ab4831778eca980d7e11d',
    messagingSenderId: '141997769768',
    projectId: 'capdog-279c5',
    authDomain: 'capdog-279c5.firebaseapp.com',
    storageBucket: 'capdog-279c5.appspot.com',
    measurementId: 'G-2D0SECFEQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASvwPj26qisd-qTugly7HCJJf3p8dauaY',
    appId: '1:141997769768:android:db8d5f16015c0e2fd7e11d',
    messagingSenderId: '141997769768',
    projectId: 'capdog-279c5',
    storageBucket: 'capdog-279c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVeai_auoDoN892qM97nE-3t3RVTsE_Q',
    appId: '1:141997769768:ios:c28ad6d1efd1a7bad7e11d',
    messagingSenderId: '141997769768',
    projectId: 'capdog-279c5',
    storageBucket: 'capdog-279c5.appspot.com',
    iosClientId: '141997769768-qmeujc3ruupj4933es616b21jr0nu8f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.capdog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVeai_auoDoN892qM97nE-3t3RVTsE_Q',
    appId: '1:141997769768:ios:c28ad6d1efd1a7bad7e11d',
    messagingSenderId: '141997769768',
    projectId: 'capdog-279c5',
    storageBucket: 'capdog-279c5.appspot.com',
    iosClientId: '141997769768-qmeujc3ruupj4933es616b21jr0nu8f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.capdog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7pYdGxyFPDgRQT7tJPUwb040eoWAtup0',
    appId: '1:141997769768:web:957402c2eec2de46d7e11d',
    messagingSenderId: '141997769768',
    projectId: 'capdog-279c5',
    authDomain: 'capdog-279c5.firebaseapp.com',
    storageBucket: 'capdog-279c5.appspot.com',
    measurementId: 'G-HHRQ228M7Y',
  );
}
